name: Run Trivy to JIRA

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # Allows to run this workflow manually from the Actions tab

jobs:
  run-trivy-to-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable caching
        uses: actions/cache@v4
        with:
          key: trivy-sbom-cache
          path: sbom/

      - name: Download Trivy
        run: wget -q https://github.com/aquasecurity/trivy/releases/download/v0.49.1/trivy_0.49.1_Linux-64bit.tar.gz

      - name: Extract Trivy
        run: tar -xf trivy_0.49.1_Linux-64bit.tar.gz

      - name: Add Trivy to PATH
        run: echo "$(pwd)" >> $GITHUB_PATH

      - name: Synchronize Trivy result to JIRA
        uses: security-chain-demo/github-actions/.github/actions/sync-trivy-to-jira@master
        with:
          services: services.json
          min_severity: ${{ vars.MIN_SEVERITY }}
          jira_project_key: ${{ vars.JIRA_PROJECT_KEY }}
          jira_issuetype_name: ${{ vars.JIRA_ISSUETYPE_NAME }}
          jira_service_field_id: ${{ vars.JIRA_SERVICE_FIELD_ID }}
          jira_service_field_name: ${{ vars.JIRA_SERVICE_FIELD_NAME }}
          jira_team_field_id: ${{ vars.JIRA_TEAM_FIELD_ID }}
          jira_cve_id_field_id: ${{ vars.JIRA_CVE_ID_FIELD_ID }}
          jira_cve_id_field_name: ${{ vars.JIRA_CVE_ID_FIELD_NAME }}
          jira_cve_status_field_id: ${{ vars.JIRA_CVE_STATUS_FIELD_ID }}
          jira_priority_ids: ${{ vars.JIRA_PRIORITY_IDS }}
        env:
          JIRA_DOMAIN: ${{ vars.JIRA_DOMAIN }}
          JIRA_EMAIL: ${{ vars.JIRA_EMAIL }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}

      - name: Expose SBOMs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sboms
          path: sbom/
          if-no-files-found: error
          compression-level: 9 # JSON compresses nicely :-D
